/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BasicNFTContract } from "./BasicNFT";
import { ClientTokenContract } from "./ClientToken";
import { CollateralizedNFTLendingContract } from "./CollateralizedNFTLending";
import { ConvertLibContract } from "./ConvertLib";
import { ERC165Contract } from "./ERC165";
import { ERC20Contract } from "./ERC20";
import { ERC721Contract } from "./ERC721";
import { ERC721EnumerableContract } from "./ERC721Enumerable";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { MetaCoinContract } from "./MetaCoin";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "BasicNFT"): BasicNFTContract;
      require(name: "ClientToken"): ClientTokenContract;
      require(
        name: "CollateralizedNFTLending"
      ): CollateralizedNFTLendingContract;
      require(name: "ConvertLib"): ConvertLibContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721Enumerable"): ERC721EnumerableContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "MetaCoin"): MetaCoinContract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export { BasicNFTContract, BasicNFTInstance } from "./BasicNFT";
export { ClientTokenContract, ClientTokenInstance } from "./ClientToken";
export {
  CollateralizedNFTLendingContract,
  CollateralizedNFTLendingInstance,
} from "./CollateralizedNFTLending";
export { ConvertLibContract, ConvertLibInstance } from "./ConvertLib";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721EnumerableContract,
  ERC721EnumerableInstance,
} from "./ERC721Enumerable";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { MetaCoinContract, MetaCoinInstance } from "./MetaCoin";
export { OwnableContract, OwnableInstance } from "./Ownable";
